### ISSUE TITLE
prism mock server(openapi.yml)

### ISSUE THREAD

**Issue by JamieLee0510** [groq/groq-typescript#23]
Thanks for the great work!
However, I have read the `CONTRIBUTING.md` and there needs a prism mock server to run groq-typescript test case.
I wonder is it possible to provide the mock `openapi.yml` file?

**Comment by JamieLee0510** [comment]
😂 just found it on the [document](https://docs.api.groq.com/md/openai.oas.html) 
will close this issue

**Comment by gradenr** [comment]
We haven't published an OpenAPI spec.  The link you found is deprecated because that API is being removed.

If you're thinking about contributing, most of this SDK is generated, so the changes that can be made directly to this codebase are small.

Can you let me know what you are attempting to do so I can point you in the right direction?

**Comment by JamieLee0510** [comment]
Thanks for the reply.
Yes I'm just want to take part in the contributions, but encounter the issue while running the test-cases ( due to prism mock server)

I just wonder what the process should contributors go through before committing?
